version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "laura-lucciola"    
    commit-message:
      prefix: "chore(deps): npm"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "laura-lucciola"    
    commit-message:
      prefix: "chore(deps): github-actions"
    
